language: ruby

sudo: required
addons:
  postgresql: "9.6"

services:
  - postgresql
  
rvm:
  - ruby 2.5.1
env:
  - DB=postgres
  - RACK_ENV=test

install:
  - bundle install

before_script:
  - rake db:create

script: bundle exec rake
